### Get Authentication Token
POST {{auth-url}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=client_credentials&client_id={{intro-client-id}}&client_secret={{intro-client-secret}}

> {%
  client.global.set("access_token", response.body.access_token);
  client.global.set("refresh_token", response.body.refresh_token);
  client.log(client.global.get("access_token"));
  client.log(client.global.get("refresh_token"));
%}

### Unauthorized Call
GET {{time-service}}/now
Accept: application/json

### Authorized Call
GET {{time-service}}/now
Authorization: Bearer {{access_token}}

### Token Introspection
POST {{auth-url}}/auth/realms/{{realm}}/protocol/openid-connect/token/introspect
Authorization: Basic {{intro-client-id}} {{intro-client-secret}}
Content-Type: application/x-www-form-urlencoded
Accept: application/json

token={{access_token}}

### Refresh Token
POST {{auth-url}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token={{refresh_token}}&client_id={{intro-client-id}}&client_secret={{intro-client-secret}}


### Get Authentication Token By Resource Owner Password Credentials Grant Flow
POST {{auth-url}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=password&username={{username}}&password={{password}}&client_id=manualtest&client_secret=112278af-a456-47fc-87df-becc6e6e1fb0

> {%
  client.global.set("client_access_token", response.body.access_token);
  client.global.set("client_refresh_token", response.body.refresh_token);
  client.log(client.global.get("client_access_token"));
  client.log(client.global.get("client_refresh_token"));
%}


### Get Authentication Token By Resource Owner Password Credentials Grant Flow
POST {{auth-url}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=password&username={{username}}&password={{password}}&client_id={{manual-test-client-id}}&client_secret={{manual-test-client-secret}}

> {%
  client.global.set("client_access_token", response.body.access_token);
  client.global.set("client_refresh_token", response.body.refresh_token);
  client.log(client.global.get("client_access_token"));
  client.log(client.global.get("client_refresh_token"));
%}
