global:
  scrape_interval: 5s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'auction-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
#    basic_auth:
#      username: 'metrics'
#      password: 'secretkey'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8090']
        labels:
          service: auction-service
