spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8200/auth/realms/speedbay/protocol/openid-connect/token/introspect
          client-id: introspection-client
          client-secret: e51d2e3b-0810-4963-8d4a-777449855448