spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8200/auth/realms/cloudbay/protocol/openid-connect/token/introspect
          client-id: introspection-client
          client-secret: 9a149149-1355-4531-85ba-32477d48c9de