{
 "title": "Logs, Traces, Metrics SPRING",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "traceID",
    "label": "Trace ID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Logs with trace ID $traceID",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{traceID=\"$traceID\"}"
    }
   ]
  },
  {
   "title": "Trace View for trace with id $traceID",
   "type": "traces",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 10 },
   "targets": [
    { "query": "$traceID" }
   ]
  },
  {
   "title": "latency for All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{uri=~\".*\"}"
    },
    {
     "expr": "{uri=~\".*\"}"
    },
    {
     "expr": "{uri=~\".*\"}"
    }
   ]
  }
 ]
}