@startuml

!include ../styling.iuml

actor "User Agent"
participant "Keycloak"
participant "AbstractAuthenticationProcessingFilter"
participant "AuthenticationManager"
participant "OAuth2LoginAuthenticationProvider"
participant "OAuth2LoginAuthenticationProvider"


"User Agent" -> "AbstractAuthenticationProcessingFilter": "call /login/oauth2/code/keycloak"

"AbstractAuthenticationProcessingFilter" -> "AbstractAuthenticationProcessingFilter": "attemptAuthentication"
"AbstractAuthenticationProcessingFilter" -> "HttpSessionOAuth2AuthorizationRequestRepository": "removeAuthorizationRequest"
"AbstractAuthenticationProcessingFilter" -> "ClientRegistrationRepository": "findByRegistrationId"
"AbstractAuthenticationProcessingFilter" -> "ClientRegistrationRepository": "findByRegistrationId"

"AbstractAuthenticationProcessingFilter" -> "AuthenticationManager" : authenticate
"AuthenticationManager" -> "OAuth2LoginAuthenticationProvider" : authenticate
"OAuth2LoginAuthenticationProvider" -> "OAuth2AuthorizationCodeAuthenticationProvider" : authenticate
"OAuth2LoginAuthenticationProvider" <- "OAuth2AuthorizationCodeAuthenticationProvider" : authenticate
"AuthenticationManager" <- "OAuth2LoginAuthenticationProvider" : authenticate





@enduml