@startuml

!include ../styling.iuml

actor "User Agent"
participant "Keycloak\n"
participant "FilterProxyChain\n"
participant "Exception\nTranslationFilter"
participant "Delegating\nAuthenticationEntryPoint"

participant "FilterSecurity\nInterceptor"

"User Agent" -> "FilterProxyChain\n": call /secure.html

"FilterProxyChain\n" -> "FilterSecurity\nInterceptor": invoke
"FilterSecurityInterceptor\n" -> "FilterSecurity\nInterceptor": beforeInvoke
"FilterSecurityInterceptor\n" -> "AccessDecision\n": decide \n(anonymousAuthenticationToken,..)
"Exception\nTranslationFilter" <- "AccessDecision\n": throw AccessDeniedException
"Exception\nTranslationFilter" -> "Exception\nTranslationFilter": handleSpringSecurityException
"Exception\nTranslationFilter" -> "Exception\nTranslationFilter": sendStartAuthentication
"Exception\nTranslationFilter" -> "Delegating\nAuthenticationEntryPoint": commence
"User Agent" <- "Delegating\nAuthenticationEntryPoint": redirect /oauth2/authorization/keycloak




@enduml