@startuml

!include ../styling.iuml


actor "User Agent"
participant "AbstractAuthentication\nProcessingFilter"
participant "AbstractAuthentication\nProcessingFilter"
participant "HttpSessionOAuth2\nAuthorizationRequestRepository"
participant "ClientRegistration\nRepository"
participant "Authentication\nManager"
participant "OAuth2Login\nAuthenticationProvider"

"User Agent" -> "AbstractAuthentication\nProcessingFilter": "call /login/oauth2/code/keycloak"

"AbstractAuthentication\nProcessingFilter" -> "AbstractAuthentication\nProcessingFilter": "attemptAuthentication"
"AbstractAuthentication\nProcessingFilter" -> "HttpSessionOAuth2\nAuthorizationRequestRepository": "removeAuthorizationRequest"
"AbstractAuthentication\nProcessingFilter" -> "ClientRegistration\nRepository": "findByRegistrationId"
"AbstractAuthentication\nProcessingFilter" -> "ClientRegistration\nRepository": "findByRegistrationId"

"AbstractAuthentication\nProcessingFilter" -> "Authentication\nManager" : authenticate
"Authentication\nManager" -> "OAuth2Login\nAuthenticationProvider" : authenticate
"OAuth2Login\nAuthenticationProvider" -> "OAuth2AuthorizationCode\nAuthenticationProvider" : authenticate
"OAuth2Login\nAuthenticationProvider" <- "OAuth2AuthorizationCode\nAuthenticationProvider" : authenticate
"Authentication\nManager" <- "OAuth2Login\nAuthenticationProvider" : authenticate


@enduml