@startuml

!include ../styling.iuml

actor "User Agent"
participant "Keycloak"
participant "FilterProxyChain"
participant "OAuth2AuthorizationRequestRedirectFilter"

"User Agent" -> "OAuth2AuthorizationRequestRedirectFilter": call /oauth2/authorization/keycloak
"User Agent" <- "OAuth2AuthorizationRequestRedirectFilter": redirect 302: to /auth endpoint

"User Agent" -> "Keycloak": call to /auth endpoint
"User Agent" <- "Keycloak": "ok 200: Login Page"
"User Agent" -> "Keycloak": "user credentials"
"User Agent" <- "Keycloak": redirect /login/oauth2/code/keycloak



@enduml