hide empty members
skinparam shadowing true
skinparam componentStyle uml2
skinparam nodeBorderColor #194b7d
skinparam nodeBackgroundColor #FEFEFE
skinparam nodeArrowColor #194b7d
skinparam actorBorderColor #194b7d
skinparam actorBackgroundColor #FEFEFE
skinparam actorArrowColor #194b7d
skinparam databaseBorderColor #194b7d
skinparam databaseBackgroundColor #FEFEFE
skinparam databaseArrowColor #194b7d
skinparam classBorderColor #194b7d
skinparam classBackgroundColor #FEFEFE
skinparam classArrowColor #194b7d
skinparam groupInheritance 3
skinparam groupAggregation 3
skinparam sequenceArrowColor #194b7d
skinparam sequenceBorderColor #194b7d
skinparam sequenceBackgroundColor #FEFEFE
skinparam sequenceParticipantArrowColor #194b7d
skinparam sequenceParticipantBorderColor #194b7d
skinparam sequenceParticipantBackgroundColor #FEFEFE
skinparam sequenceLifeLineBorderColor #194b7d
skinparam sequenceLifeLineBackgroundColor #FEFEFE
skinparam sequenceLifeLineArrowColor #194b7d
skinparam classBorderColor #194b7d